version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  ignore:
  - dependency-name: ember-cli
    versions:
    - ">= 0"
  - dependency-name: eslint-plugin-ember
    versions:
    - 10.1.2
    - 10.2.0
    - 10.3.0
    - 10.4.1
  - dependency-name: release-it
    versions:
    - 14.5.0
    - 14.5.1
  - dependency-name: ember-cli-babel
    versions:
    - 7.26.1
    - 7.26.2
    - 7.26.3
  - dependency-name: ember-template-lint
    versions:
    - 3.1.1
    - 3.2.0
  - dependency-name: highlight.js
    versions:
    - 10.7.1
  - dependency-name: hosted-git-info
    versions:
    - 4.0.1
  - dependency-name: ember-cli-htmlbars
    versions:
    - 5.3.2
    - 5.4.0
    - 5.6.0
    - 5.6.2
    - 5.6.3
    - 5.7.0
  - dependency-name: postcss
    versions:
    - 8.2.6
    - 8.2.8
  - dependency-name: "@fullhuman/postcss-purgecss"
    versions:
    - 4.0.0
    - 4.0.2
  - dependency-name: "@glimmer/syntax"
    versions:
    - 0.76.0
  - dependency-name: ember-concurrency
    versions:
    - 2.0.0
    - 2.0.1
  - dependency-name: ember-router-scroll
    versions:
    - 4.0.1
    - 4.0.2
