name: Publish Addon Docs

on:
  push:
    branches:
      - main
      - master
    tags:
      - "**"
jobs:
  build:
    env:
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install --no-lockfile
      - name: Check for tags
        id: check-tags
        run: |
          # Get tags pointing to the current commit
          TAGS=$(git tag --points-at $GITHUB_SHA)
          echo "Tags found: $TAGS"
          
          # Save whether tags exist as an output variable
          if [ -z "$TAGS" ]; then
            echo "has_tag=false" >> $GITHUB_ENV
          else
            echo "has_tag=true" >> $GITHUB_ENV
          fi
      - name: Deploy Docs
        if: env.has_tag == 'false' || (env.has_tag == 'true' && !startsWith(github.ref, 'refs/heads/main'))
        run: pnpm ember deploy production